# Generated by Django 6.0.3 on 2026-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
